// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJRHsNzo20LdSvKAcWSu3t9q580WhOQzM',
    appId: '1:884931733927:web:530946d725c98e61732e82',
    messagingSenderId: '884931733927',
    projectId: 'frist-ecommerce',
    authDomain: 'frist-ecommerce.firebaseapp.com',
    storageBucket: 'frist-ecommerce.firebasestorage.app',
    measurementId: 'G-W84HD5CVNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Skdrx46wnRxAvhdBibQnk9HauqPhK1g',
    appId: '1:884931733927:android:2fd55c61c55832d0732e82',
    messagingSenderId: '884931733927',
    projectId: 'frist-ecommerce',
    storageBucket: 'frist-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH053jsXf3ZyaawIKv5va1S7Baxot9laM',
    appId: '1:884931733927:ios:63d4411a36923fdd732e82',
    messagingSenderId: '884931733927',
    projectId: 'frist-ecommerce',
    storageBucket: 'frist-ecommerce.firebasestorage.app',
    iosBundleId: 'com.aacl.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH053jsXf3ZyaawIKv5va1S7Baxot9laM',
    appId: '1:884931733927:ios:63d4411a36923fdd732e82',
    messagingSenderId: '884931733927',
    projectId: 'frist-ecommerce',
    storageBucket: 'frist-ecommerce.firebasestorage.app',
    iosBundleId: 'com.aacl.flutterEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJRHsNzo20LdSvKAcWSu3t9q580WhOQzM',
    appId: '1:884931733927:web:f0d1e4957bad6927732e82',
    messagingSenderId: '884931733927',
    projectId: 'frist-ecommerce',
    authDomain: 'frist-ecommerce.firebaseapp.com',
    storageBucket: 'frist-ecommerce.firebasestorage.app',
    measurementId: 'G-BPNTC8WTCL',
  );
}
